### ISSUE TITLE
router 이동시에 데이터 전송

### ISSUE THREAD

**Issue by ranbly** [devjin0617/vuejs-eventbus-example#1]
> vue.js 를 공부하고 있는데 한 가지 여쭤볼게 있습니다~~
> 지금은 div id="app"내에 SenderApp, RecieverApp이 동시에 있을때 데이터를 넘겨주는 방식으로 되어있는데 router를 사용할 때에는 다른 컴포넌트들간에 데이터를 어떻게 넘겨줘야할까요 ..?

**Comment by devjin0617** [comment]
@ranbly 일반적으로 router까지 껴서 사용하신다면 중앙에서 데이터를 관리하는게 편하실거예요. 그것을 보조해주는 것이 `vuex`라는 상태를 관리해주는 라이브러리가 있습니다. (글로벌 변수라고 생각하시면 처음에 접근하기 좋으실거예요)

vuejs관련 라이브러리도 한글화가 잘 되어 있어서 아래 URL참고하시면 될 것 같습니다 😄 

https://vuex.vuejs.org/kr/

**Comment by ranbly** [comment]
감사합니다 !! 공식문서에도 vuex 설명이 나와있었네요 :)

**Comment by devjin0617** [comment]
@ranbly 공식문서에 모든 내용이 있기는 하지만, 자세하게 적혀있지 않아 애매한 부분들이 있습니다. 국내 Vuejs사용자들로 구성된 페이스북, 슬랙 채널들이 있으니 궁금한점들을 물어보면 다같이 고민해줄거예요 😄 

- Vue.js 한국어 사용자 Facebook 그룹
https://www.facebook.com/groups/vuejs.korea/

- Vue.js 한국어 사용자 Slack 채팅방
https://vuejs-korea.signup.team/
